// Generated by: supabase gen types typescript --local > lib/database.types.ts
// Placeholder until M1 lands the schema migrations — regenerate once
// supabase/migrations defines the domain tables. Do not hand-edit.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
